# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.wc.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'wc', 'function_path': 'animated_java:wc/animations/animation.model.crawling/play'}
tag @s add aj.wc.animation.animation.model.crawling.playing
scoreboard players set @s aj.animation.model.crawling.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:wc/animations/animation.model.crawling/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only