# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.125f,0f,0f,-1f,0.6734f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_upper_group) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.125f,0f,0f,-1f,0.2984f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_lower_group) {transformation: [-1f,0f,0f,0f,0f,0.7343f,0.6788f,0.3625f,0f,0.6788f,-0.7343f,-0.0172f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_upper_arm_group) {transformation: [-1f,0f,0f,-0.25f,0f,1f,0f,0.125f,0f,0f,-1f,0.5484f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_lower_arm_group) {transformation: [-1f,0f,0f,-0.3438f,0f,1f,0f,0.125f,0f,0f,-1f,0.2984f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_upper_arm_group) {transformation: [-1f,0f,0f,0.25f,0f,1f,0f,0.125f,0f,0f,-1f,0.5484f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_lower_arm_group) {transformation: [-1f,0f,0f,0.3437f,0f,1f,0f,0.125f,0f,0f,-1f,0.2984f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_upper_leg_group) {transformation: [-1f,0f,0f,-0.1187f,0f,0.7343f,-0.6788f,0.3625f,0f,-0.6788f,-0.7343f,-0.0172f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_upper_leg_group) {transformation: [-1f,0f,0f,0.1188f,0f,0.7343f,-0.6788f,0.3625f,0f,-0.6788f,-0.7343f,-0.0172f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}