# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.125f,0f,0f,-1f,0.7016f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_upper_group) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.125f,0f,0f,-1f,0.3266f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_lower_group) {transformation: [-1f,0f,0f,0f,0f,0.809f,0.5878f,0.325f,0f,0.5878f,-0.809f,0.0016f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_upper_arm_group) {transformation: [-1f,0f,0f,-0.25f,0f,1f,0f,0.125f,0f,0f,-1f,0.5766f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_lower_arm_group) {transformation: [-1f,0f,0f,-0.3438f,0f,1f,0f,0.125f,0f,0f,-1f,0.3266f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_upper_arm_group) {transformation: [-1f,0f,0f,0.25f,0f,1f,0f,0.125f,0f,0f,-1f,0.5766f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_lower_arm_group) {transformation: [-1f,0f,0f,0.3437f,0f,1f,0f,0.125f,0f,0f,-1f,0.3266f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_upper_leg_group) {transformation: [-1f,0f,0f,-0.1187f,0f,0.809f,-0.5878f,0.325f,0f,-0.5878f,-0.809f,0.0016f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_upper_leg_group) {transformation: [-1f,0f,0f,0.1188f,0f,0.809f,-0.5878f,0.325f,0f,-0.5878f,-0.809f,0.0016f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}