# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.125f,0f,0f,-1f,0.7766f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_upper_group) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.125f,0f,0f,-1f,0.4016f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_lower_group) {transformation: [-1f,0f,0f,0f,0f,0.9511f,0.309f,0.225f,0f,0.309f,-0.9511f,0.0516f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_upper_arm_group) {transformation: [-1f,0f,0f,-0.25f,0f,1f,0f,0.125f,0f,0f,-1f,0.6516f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_lower_arm_group) {transformation: [-1f,0f,0f,-0.3438f,0f,1f,0f,0.125f,0f,0f,-1f,0.4016f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_upper_arm_group) {transformation: [-1f,0f,0f,0.25f,0f,1f,0f,0.125f,0f,0f,-1f,0.6516f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_lower_arm_group) {transformation: [-1f,0f,0f,0.3437f,0f,1f,0f,0.125f,0f,0f,-1f,0.4016f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_upper_leg_group) {transformation: [-1f,0f,0f,-0.1187f,0f,0.9511f,-0.309f,0.225f,0f,-0.309f,-0.9511f,0.0516f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_upper_leg_group) {transformation: [-1f,0f,0f,0.1187f,0f,0.9511f,-0.309f,0.225f,0f,-0.309f,-0.9511f,0.0516f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}