# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.125f,0f,0f,-1f,0.8047f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_upper_group) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.125f,0f,0f,-1f,0.4297f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_lower_group) {transformation: [-1f,0f,0f,0f,0f,0.9808f,0.1951f,0.1875f,0f,0.1951f,-0.9808f,0.0703f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_upper_arm_group) {transformation: [-1f,0f,0f,-0.25f,0f,1f,0f,0.125f,0f,0f,-1f,0.6797f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_lower_arm_group) {transformation: [-1f,0f,0f,-0.3438f,0f,1f,0f,0.125f,0f,0f,-1f,0.4297f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_upper_arm_group) {transformation: [-1f,0f,0f,0.25f,0f,1f,0f,0.125f,0f,0f,-1f,0.6797f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_lower_arm_group) {transformation: [-1f,0f,0f,0.3437f,0f,1f,0f,0.125f,0f,0f,-1f,0.4297f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_upper_leg_group) {transformation: [-1f,0f,0f,-0.1187f,0f,0.9808f,-0.1951f,0.1875f,0f,-0.1951f,-0.9808f,0.0703f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_upper_leg_group) {transformation: [-1f,0f,0f,0.1187f,0f,0.9808f,-0.1951f,0.1875f,0f,-0.1951f,-0.9808f,0.0703f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}