# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.wc.root] run return 0
execute on passengers if entity @s[tag=aj.wc.data] unless data entity @s {data:{rigHash: 'e97746e06d96e272244a9864d22fbac847b6830d9ea8444715f72e3b564c3ca9'}} on vehicle run function animated_java:wc/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1