# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:wc/animations/animation.model.crawling/zzz/apply_frame {frame: 42}
scoreboard players add @s aj.animation.model.crawling.frame 1