# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.wc.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'wc', 'function_path': 'animated_java:wc/variants/default/apply'}
execute on passengers if entity @s[tag=aj.wc.bone.head] run function animated_java:wc/variants/default/zzz/apply_to_bone_head
execute on passengers if entity @s[tag=aj.wc.bone.body_upper_group] run function animated_java:wc/variants/default/zzz/apply_to_bone_body_upper_group
execute on passengers if entity @s[tag=aj.wc.bone.body_lower_group] run function animated_java:wc/variants/default/zzz/apply_to_bone_body_lower_group
execute on passengers if entity @s[tag=aj.wc.bone.right_upper_arm_group] run function animated_java:wc/variants/default/zzz/apply_to_bone_right_upper_arm_group
execute on passengers if entity @s[tag=aj.wc.bone.right_lower_arm_group] run function animated_java:wc/variants/default/zzz/apply_to_bone_right_lower_arm_group
execute on passengers if entity @s[tag=aj.wc.bone.left_upper_arm_group] run function animated_java:wc/variants/default/zzz/apply_to_bone_left_upper_arm_group
execute on passengers if entity @s[tag=aj.wc.bone.left_lower_arm_group] run function animated_java:wc/variants/default/zzz/apply_to_bone_left_lower_arm_group
execute on passengers if entity @s[tag=aj.wc.bone.right_upper_leg_group] run function animated_java:wc/variants/default/zzz/apply_to_bone_right_upper_leg_group
execute on passengers if entity @s[tag=aj.wc.bone.right_lower_leg_group] run function animated_java:wc/variants/default/zzz/apply_to_bone_right_lower_leg_group
execute on passengers if entity @s[tag=aj.wc.bone.left_upper_leg_group] run function animated_java:wc/variants/default/zzz/apply_to_bone_left_upper_leg_group
execute on passengers if entity @s[tag=aj.wc.bone.left_lower_leg_group] run function animated_java:wc/variants/default/zzz/apply_to_bone_left_lower_leg_group
return 1