# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wc.node.head] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_head set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wc.node.body_upper_group] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_body_upper_group set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wc.node.body_lower_group] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_body_lower_group set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wc.node.right_upper_arm_group] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right_upper_arm_group set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wc.node.right_lower_arm_group] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right_lower_arm_group set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wc.node.left_upper_arm_group] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left_upper_arm_group set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wc.node.left_lower_arm_group] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left_lower_arm_group set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wc.node.right_upper_leg_group] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right_upper_leg_group set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wc.node.right_lower_leg_group] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right_lower_leg_group set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wc.node.left_upper_leg_group] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left_upper_leg_group set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wc.node.left_lower_leg_group] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left_lower_leg_group set from storage aj:uuid main.out